Ping
bridge-scrims/bridge-scrims-bot pull request #37
Opened 2022-03-03 10:39 UTC by NiteBlock

2022-03-04 16:30 UTC, dtomvan requested changes
I've done some nitpicking

2022-03-04 16:30 UTC, dtomvan commented on src/commands/mod.rs
> +    async fn remove_cooldown(inner: Arc<Mutex<Vec<Cooldown>>>, cooldown: Cooldown) {
Why not use `&self` instead of `inner`?

2022-03-04 16:30 UTC, dtomvan commented on src/commands/mod.rs
> +        *c = x
```suggestion
        if let Some(i) = c.iter().position(|v| v == &cooldown) {
            c.swap_remove(i);
        }
```

2022-03-04 16:30 UTC, dtomvan commented on src/commands/mod.rs
> +        None
```suggestion
        self.0.lock().await.iter().find(|cooldown| {
            if key != cooldown.key && cooldown.key.is_some() {
                return false;
            };
            match cooldown.cooldown_info {
                CooldownType::Global => true,
                CooldownType::User(uid) => uid == user,
            }
        })
        .map(|cooldown| {
            cooldown.duration - (cooldown.exipre - cooldown.duration).elapsed().unwrap()
        })
```

2022-03-04 17:29 UTC, NiteBlock commented on src/commands/mod.rs
> +#[derive(Clone, Copy, PartialEq)]
ok

2022-03-04 17:29 UTC, NiteBlock commented on src/commands/mod.rs
> +pub struct Cooldowns(Arc<Mutex<Vec<Cooldown>>>);
I think so

2022-03-04 17:30 UTC, NiteBlock commented on src/commands/mod.rs
> +    async fn remove_cooldown(inner: Arc<Mutex<Vec<Cooldown>>>, cooldown: Cooldown) {
it drops the value

2022-03-04 17:36 UTC, NiteBlock commented on src/commands/mod.rs
> +    exipre: SystemTime,
oops

2022-03-04 20:25 UTC, dtomvan approved these changes

2022-03-05 06:45 UTC, NiteBlock commented
Oh thx I was gonna do it today

2022-03-05 06:46 UTC, merged